version: '3.8'

services:
  odinbeats-postgres:
    image: postgres
    ports:
      - 5434:5432
    environment:
      - POSTGRES_PASSWORD=toor
      - POSTGRES_USER=postgres
      - POSTGRES_DB=odinbeats
    networks:
      - odinbeats
networks:
  odinbeats: